### ISSUE TITLE
TwInit not found

### ISSUE THREAD

**Issue by flecheria** [rougier/atb-python#3]
Hi, I'm running atb inside the pupil project but it told me that TwInit not found?
I was thinking if I have to put the file AntTweakBar.h in some specific place.
BTW this is the prompt. Thanks

```
C:\workspace_fork\pupil_w\pupil\pupil_src\capture>python main.py
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    from eye import eye
  File "C:\workspace_fork\pupil_w\pupil\pupil_src\capture\eye.py", line 18, in <module>
    import atb
  File "C:\workspace_fork\pupil_w\pupil\pupil_src\shared_modules\atb\__init__.py", line 16, in <module>
    from raw import *
  File "C:\workspace_fork\pupil_w\pupil\pupil_src\shared_modules\atb\raw.py", line 51, in <module>
    TwInit         = __dll__.TwInit
  File "C:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'TwInit' not found
```

**Comment by rougier** [comment]
What is your machine/OS and python/ATB version ?

**Comment by flecheria** [comment]
Sorry for the delay. I was working on a Windows 7 64 bit with Python 32 bit and AntTweakBar 1.16.
I'm updating Python to 64 bit, maybe it was for this... I will try when I finish to install all the things

**Comment by rougier** [comment]
ok
